# Generated by Django 2.0.2 on 2018-03-29 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singletournaments', '0002_remove_singleeliminationtournament_rules'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ruleset',
        ),
    ]
