# Generated by Django 2.0.4 on 2018-04-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='team2reported',
            field=models.BooleanField(default=False),
        ),
    ]
