# Generated by Django 2.0.4 on 2018-04-05 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teaminvite_hasperms'),
        ('matches', '0002_auto_20180404_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1reportedwinner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1reportedwinner', to='teams.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2reportedwinner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2reportedwinner', to='teams.Team'),
        ),
    ]
