# Generated by Django 2.2.15 on 2020-12-09 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20201209_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='map',
        ),
        migrations.AddField(
            model_name='match',
            name='map_pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mappoolchoice', to='matches.MapPoolChoice'),
        ),
        migrations.AlterField(
            model_name='match',
            name='maps',
            field=models.ManyToManyField(to='matches.MapChoice'),
        ),
    ]
