# Generated by Django 2.0.5 on 2018-10-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('matches', '0002_auto_20181012_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='info',
            field=models.TextField(default='Match Info: '),
        ),
    ]
