# Generated by Django 2.0.4 on 2018-04-05 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_matchdispute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchdispute',
            old_name='team1proof',
            new_name='teamproof',
        ),
        migrations.RenameField(
            model_name='matchdispute',
            old_name='team1reporter',
            new_name='teamreporter',
        ),
        migrations.RemoveField(
            model_name='matchdispute',
            name='team2proof',
        ),
        migrations.RemoveField(
            model_name='matchdispute',
            name='team2reporter',
        ),
    ]
