# Generated by Django 2.2.15 on 2020-12-15 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_auto_20201209_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loser', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='maps',
            field=models.ManyToManyField(blank=True, to='matches.MapChoice'),
        ),
        migrations.AlterField(
            model_name='match',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SportChoice', to='matches.SportChoice'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='champions', to='teams.Team'),
        ),
    ]
