# Generated by Django 2.0.8 on 2018-10-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_auto_20181018_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bye_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='bye_2',
            field=models.BooleanField(default=False),
        ),
    ]
