# Generated by Django 2.0.7 on 2019-01-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_auto_20181029_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='game_images')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='platform_images')),
            ],
        ),
    ]
