# Generated by Django 2.0.1 on 2018-04-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_auto_20180405_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdispute',
            name='teamproof_1',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='matchdispute',
            name='teamproof_2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='matchdispute',
            name='teamproof_3',
            field=models.URLField(blank=True),
        ),
    ]
