# Generated by Django 2.0.1 on 2018-04-07 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_auto_20180406_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'matches'},
        ),
    ]
