# Generated by Django 2.2.15 on 2021-01-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_match_config_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='server',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
