# Generated by Django 2.2.12 on 2021-05-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_auto_20210101_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='conference_match',
            field=models.BooleanField(default=True),
        ),
    ]
