# Generated by Django 2.0 on 2018-04-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_auto_20180406_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='start',
        ),
    ]
