# Generated by Django 2.1.5 on 2019-03-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_auto_20190315_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappoolchoice',
            name='maps',
            field=models.ManyToManyField(blank=True, null=True, to='matches.MapChoice'),
        ),
    ]
