# Generated by Django 2.0 on 2018-04-07 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_remove_match_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='awayteam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awayteam', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='hometeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hometeam', to='teams.Team'),
        ),
    ]
