# Generated by Django 2.0.4 on 2018-04-25 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_match_disputed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team1reportedwinner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1reportedwinner', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2reportedwinner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2reportedwinner', to='teams.Team'),
        ),
    ]
