# Generated by Django 2.1.5 on 2019-03-29 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_auto_20190328_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapchoice',
            name='map_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
