# Generated by Django 2.0.4 on 2018-04-28 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_auto_20180424_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdispute',
            name='teamreporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1Disputer', to=settings.AUTH_USER_MODEL),
        ),
    ]
