# Generated by Django 2.1.5 on 2019-03-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_auto_20190328_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappoolchoice',
            name='maps',
            field=models.ManyToManyField(blank=True, to='matches.MapChoice'),
        ),
    ]
