# Generated by Django 2.2.2 on 2019-06-05 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0013_auto_20190328_2022'),
        ('matches', '0008_match_type'),
    ]

    operations = [
    ]
