# Generated by Django 2.0.4 on 2018-04-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0013_auto_20180427_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdispute',
            name='teamproof_1',
            field=models.URLField(),
        ),
    ]
