# Generated by Django 2.0.4 on 2018-05-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0014_auto_20180427_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchdispute',
            name='teamproof',
        ),
        migrations.AddField(
            model_name='match',
            name='matchnum',
            field=models.SmallIntegerField(default=0),
        ),
    ]
