# Generated by Django 2.0.1 on 2018-06-08 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20180607_1656'),
        ('matches', '0015_auto_20180505_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='teams.Team'),
        ),
    ]
