# Generated by Django 2.2.2 on 2020-01-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0015_auto_20190713_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='bestof',
            field=models.SmallIntegerField(choices=[(0, 'Best of 1'), (1, 'Best of 3'), (2, 'Best of 5'), (3, 'Best of 7'), (4, 'Best of 9')], default=0, null=True),
        ),
    ]
