# Generated by Django 2.2.2 on 2020-01-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0016_auto_20200108_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown sports', max_length=255)),
            ],
        ),
    ]
