# Generated by Django 2.2.7 on 2020-01-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0017_sportchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='disable_userreports',
            field=models.BooleanField(default=True),
        ),
    ]
