# Generated by Django 2.2.7 on 2020-01-15 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0019_auto_20200115_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='sports',
            new_name='sport',
        ),
    ]
