# Generated by Django 2.2.3 on 2020-04-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0021_auto_20200115_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='bestof',
            field=models.SmallIntegerField(choices=[(0, 'Best of 1'), (1, 'Best of 3'), (2, 'Best of 5'), (3, 'Best of 7'), (4, 'Best of 9')], default=0),
        ),
    ]
