# Generated by Django 2.2.14 on 2020-08-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0022_auto_20200410_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchid', models.PositiveIntegerField(default=0)),
                ('map', models.CharField(default='unknown', max_length=255)),
                ('team1', models.CharField(default='unknown', max_length=255)),
                ('team2', models.CharField(default='unknown', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StatsPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=3, max_digits=6)),
                ('kills', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('killround', models.DecimalField(decimal_places=3, max_digits=6)),
                ('adr', models.IntegerField(default=0)),
                ('ud', models.IntegerField(default=0)),
                ('ef', models.IntegerField(default=0)),
                ('f_assists', models.IntegerField(default=0)),
                ('hs', models.IntegerField(default=0)),
                ('kast', models.IntegerField(default=0)),
                ('awp_k', models.IntegerField(default=0)),
                ('twok', models.IntegerField(default=0)),
                ('threek', models.IntegerField(default=0)),
                ('fourk', models.IntegerField(default=0)),
                ('fivek', models.IntegerField(default=0)),
                ('one_v_one', models.IntegerField(default=0)),
                ('one_v_two', models.IntegerField(default=0)),
                ('one_v_three', models.IntegerField(default=0)),
                ('one_v_four', models.IntegerField(default=0)),
                ('one_v_five', models.IntegerField(default=0)),
                ('f_kills', models.IntegerField(default=0)),
                ('f_deaths', models.IntegerField(default=0)),
                ('entries', models.IntegerField(default=0)),
                ('trades', models.IntegerField(default=0)),
                ('rounds', models.IntegerField(default=0)),
                ('rf', models.IntegerField(default=0)),
                ('ra', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=0)),
            ],
        ),
    ]
