# Generated by Django 2.0 on 2018-02-18 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptainMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='captaininvite',
            name='inviter',
        ),
        migrations.RemoveField(
            model_name='captaininvite',
            name='team',
        ),
        migrations.RemoveField(
            model_name='captaininvite',
            name='user',
        ),
        migrations.AddField(
            model_name='teaminvite',
            name='captain',
            field=models.CharField(choices=[('captain', 'Captain'), ('player', 'Player')], default='player', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='captain',
            field=models.ManyToManyField(related_name='teamcaptain', through='teams.CaptainMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CaptainInvite',
        ),
        migrations.AddField(
            model_name='captainmembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='teams.Team'),
        ),
        migrations.AddField(
            model_name='captainmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captainperson', to=settings.AUTH_USER_MODEL),
        ),
    ]
