# Generated by Django 2.0.1 on 2018-03-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvite',
            name='hasPerms',
            field=models.BooleanField(default=False),
        ),
    ]
