# Generated by Django 2.0.8 on 2018-10-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='totalxp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
