# Generated by Django 2.2.15 on 2020-12-15 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='captain',
            field=models.ManyToManyField(blank=True, related_name='teamcaptain', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='matches',
            field=models.ManyToManyField(blank=True, related_name='team_matches', to='matches.Match'),
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='teamplayers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_stat',
            field=models.ManyToManyField(blank=True, related_name='match_team_stat', to='matches.TeamMatchStats'),
        ),
    ]
