# Generated by Django 2.2.15 on 2020-11-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='matches',
            field=models.ManyToManyField(related_name='team_matches', to='matches.Match'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_stat',
            field=models.ManyToManyField(related_name='match_team_stat', to='matches.TeamMatchStats'),
        ),
    ]
