# Generated by Django 2.0.5 on 2018-06-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teaminvite_hasperms'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='num_loss',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='num_win',
            field=models.SmallIntegerField(default=0),
        ),
    ]
