# Generated by Django 2.2.12 on 2020-12-02 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20201121_2203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaptainMembership',
        ),
    ]
