# Generated by Django 2.0.1 on 2018-03-04 16:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20180304_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminviteaccepted',
            name='inviter',
        ),
        migrations.RemoveField(
            model_name='teaminviteaccepted',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teaminviteaccepted',
            name='user',
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(through='teams.TeamInvite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TeamInviteAccepted',
        ),
    ]
