# Generated by Django 2.2.15 on 2020-12-31 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20201215_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tag',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
