# Generated by Django 2.0.5 on 2018-06-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20180607_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='num_loss',
            new_name='num_matchloss',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='num_win',
            new_name='num_matchwin',
        ),
        migrations.AddField(
            model_name='team',
            name='num_tournywin',
            field=models.SmallIntegerField(default=0),
        ),
    ]
