# Generated by Django 2.0.8 on 2018-11-09 21:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('teams', '0003_auto_20181012_2134'),
        ('teams', '0002_team_totalxp'),
    ]

    operations = [
    ]
