# Generated by Django 2.2.15 on 2021-07-19 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0003_team_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RosterMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined', models.DateTimeField(auto_created=True)),
                ('description', models.TextField(default='No Description')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rostermemberrole', to='teams.RosterRole')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rostermemberuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(to='teams.RosterMember')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamroster', to='teams.Team')),
            ],
        ),
    ]
