# Generated by Django 2.0.1 on 2018-06-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20180607_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='numtournyloss',
            field=models.SmallIntegerField(default=0),
        ),
    ]
