# Generated by Django 2.2.2 on 2019-06-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teams', '0005_team_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='num_wagerloss',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='num_wagerwin',
            field=models.SmallIntegerField(default=0),
        ),
    ]
