# Generated by Django 2.2.2 on 2019-07-13 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20190620_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='founder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='founder', to=settings.AUTH_USER_MODEL),
        ),
    ]
