# Generated by Django 2.2.2 on 2019-08-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_auto_20190713_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, upload_to='team_images'),
        ),
    ]
