# Generated by Django 2.2.14 on 2020-08-22 20:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0008_team_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='captain',
        ),
        migrations.AddField(
            model_name='team',
            name='captains',
            field=models.ManyToManyField(blank=True, related_name='team_captains', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='team_players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='team_players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CaptainMembership',
        ),
    ]
