# Generated by Django 2.2.15 on 2020-08-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_auto_20200822_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminvite',
            name='hasPerms',
        ),
        migrations.AlterField(
            model_name='teaminvite',
            name='captain',
            field=models.BooleanField(default=False),
        ),
    ]
