# Generated by Django 2.2.12 on 2020-12-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20201121_2203'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='captain_teams',
            field=models.ManyToManyField(related_name='profile_captain_teams', to='teams.Team'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='founder_teams',
            field=models.ManyToManyField(related_name='profile_founder_teams', to='teams.Team'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='player_teams',
            field=models.ManyToManyField(related_name='profile_player_teams', to='teams.Team'),
        ),
    ]
