# Generated by Django 2.0.2 on 2018-03-14 20:42

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180311_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(default='No Country Selected', max_length=2),
        ),
    ]
