# Generated by Django 2.0.1 on 2018-09-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0002_auto_20180803_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rank',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
