# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170804_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about_me',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='credits',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_console',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_game',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='psn',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitch_channel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_profile',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='xbl',
            field=models.CharField(default='', max_length=15),
        ),
    ]
