# Generated by Django 2.0.1 on 2018-03-15 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0003_userprofile_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownpc', models.BooleanField(default=False)),
                ('cpu', models.CharField(default='No CPU specified', max_length=30)),
                ('gpu', models.CharField(default='No GPU specified', max_length=30)),
                ('psu', models.CharField(default='No PSU specified', max_length=30)),
                ('case', models.CharField(default='No Case specified', max_length=30)),
                ('os', models.CharField(default='No OS specified', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userspecs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='battlenet',
            field=models.CharField(blank=True, default='No Battle.net Linked', max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lol',
            field=models.CharField(blank=True, default='No LOL Linked', max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='steam',
            field=models.CharField(blank=True, default='No Steam Linked', max_length=16),
        ),
    ]
