# Generated by Django 2.0.8 on 2018-10-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0003_userprofile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_verified',
            field=models.BooleanField(default=False),
        ),
    ]
