# Generated by Django 2.2.15 on 2021-01-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_alternate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='discord',
            field=models.CharField(blank=True, default='No Discord', max_length=255),
        ),
    ]
