# Generated by Django 2.2.15 on 2021-02-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210125_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='datetime',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
