# Generated by Django 2.0.5 on 2018-10-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0004_userprofile_user_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='epic',
            field=models.CharField(blank=True, default='No Epic Linked', max_length=30),
        ),
    ]
