# Generated by Django 2.0 on 2018-01-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20170821_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about_me',
            field=models.CharField(blank=True, default='Forever a mystery', max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_console',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_game',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='psn',
            field=models.CharField(blank=True, default='No PSN Linked', max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitch_channel',
            field=models.CharField(blank=True, default='No Twitch Linked', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter_profile',
            field=models.CharField(blank=True, default='No Twitter Linked', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='xbl',
            field=models.CharField(blank=True, default='No Xbox Live Linked', max_length=15),
        ),
    ]
