# Generated by Django 2.0.4 on 2018-05-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20180317_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='battlenet',
            field=models.CharField(blank=True, default='No Battle.net Linked', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lol',
            field=models.CharField(blank=True, default='No LOL Linked', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='psn',
            field=models.CharField(blank=True, default='No PSN Linked', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='steam',
            field=models.CharField(blank=True, default='No Steam Linked', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='twitter_profile',
            field=models.CharField(blank=True, default='No Twitter Linked', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='xbl',
            field=models.CharField(blank=True, default='No Xbox Live Linked', max_length=30),
        ),
    ]
