# Generated by Django 2.1.5 on 2019-02-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userprofile_epic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='xbl_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
