# Generated by Django 2.2.12 on 2021-04-29 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_tag'),
        ('profiles', '0005_auto_20210202_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='feat_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_feat_team', to='teams.Team'),
        ),
    ]
