# Generated by Django 2.2.12 on 2021-04-29 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_userprofile_feat_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='feat_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_feat_team', to='teams.Team'),
        ),
    ]
