# Generated by Django 2.1.5 on 2019-02-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20190207_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
