# Generated by Django 2.0.1 on 2018-06-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20180528_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='passes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
