# Generated by Django 2.0 on 2018-01-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_userprofile_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ip',
            field=models.CharField(default='0.0.0.0', max_length=12),
        ),
    ]
