# Generated by Django 2.0.4 on 2018-06-23 19:10

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_userprofile_passes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(default='US', max_length=2),
        ),
    ]
