# Generated by Django 2.2.12 on 2021-05-07 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20210506_1512'),
        ('profiles', '0006_auto_20210506_1542'),
    ]

    operations = [
    ]
