# Generated by Django 2.2.2 on 2019-06-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('profiles', '0008_auto_20190602_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='num_wagerloss',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='num_wagerwin',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
