# Generated by Django 2.2.12 on 2021-05-07 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_merge_20210507_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='num_trophies',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='passes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='psn_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='xbl_verified',
        ),
    ]
