# Generated by Django 2.0 on 2018-01-14 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_banneduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banneduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banned', to=settings.AUTH_USER_MODEL),
        ),
    ]
