# Generated by Django 2.2.12 on 2020-05-07 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20190620_1725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGear',
        ),
    ]
