# Generated by Django 2.2.12 on 2020-05-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_delete_usergear'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activisionid',
            field=models.CharField(blank=True, default='No Activision ID Linked', max_length=30),
        ),
    ]
