# Generated by Django 2.0.1 on 2018-02-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20180113_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='banned',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ip',
            field=models.CharField(default='0.0.0.0', max_length=16),
        ),
    ]
