# Generated by Django 2.2.12 on 2021-05-07 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20210507_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='featured_team',
        ),
    ]
