# Generated by Django 2.2.14 on 2020-08-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_userprofile_activisionid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(default='No description given')),
                ('sender', models.CharField(default='System', max_length=255)),
                ('type', models.CharField(choices=[('match', 1), ('tournament', 2), ('league', 3), ('team', 4), ('support', 5), ('news', 6), ('general', 7), ('store', 8)], default='general', max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('read', models.BooleanField(default=False)),
                ('seen', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='user_notifications', to='profiles.Notification'),
        ),
    ]
