# Generated by Django 2.2.12 on 2021-05-07 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_tag'),
        ('profiles', '0011_remove_userprofile_featured_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='featured_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_featured_team', to='teams.Team'),
        ),
    ]
