# Generated by Django 2.0.1 on 2018-02-20 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_transfer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
