# Generated by Django 2.2.15 on 2020-08-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20200813_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='pk1',
            field=models.IntegerField(default=0),
        ),
    ]
