# Generated by Django 2.2.12 on 2021-05-08 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_merge_20210507_1626'),
        ('profiles', '0012_userprofile_featured_team'),
    ]

    operations = [
    ]
