# Generated by Django 2.2.12 on 2021-08-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_merge_20210508_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
