# Generated by Django 2.0.5 on 2018-07-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('account', models.CharField(max_length=50)),
                ('credits', models.PositiveSmallIntegerField()),
                ('passes', models.PositiveSmallIntegerField()),
                ('staff', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('credits', models.DecimalField(decimal_places=0, max_digits=6)),
                ('origin', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
            ],
        ),
    ]
