# Generated by Django 2.0.2 on 2018-08-03 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('business', models.EmailField(max_length=254)),
                ('amount', models.FloatField()),
                ('item_name', models.CharField(max_length=50, validators=[
                    django.core.validators.RegexValidator(code='invalid_name',
                                                          message="Item name must not have whitespace, and must be in the format 'type_num'",
                                                          regex='^[a-zA-z]+_\\d+')])),
                ('price', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('account', models.CharField(max_length=50)),
                ('staff', models.CharField(blank=True, max_length=50)),
                ('num', models.SmallIntegerField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('credits', models.DecimalField(decimal_places=0, max_digits=6)),
                ('origin', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
            ],
        ),
    ]
