# Generated by Django 2.0.1 on 2018-02-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('credits', models.DecimalField(decimal_places=0, max_digits=6)),
                ('origin', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
            ],
        ),
    ]
