# Generated by Django 2.0.1 on 2018-06-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_transaction_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='passes',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
