# Generated by Django 2.0.1 on 2018-06-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_transaction_passes'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='staff',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
