# Generated by Django 2.0.7 on 2018-07-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='passes',
        ),
        migrations.AddField(
            model_name='transaction',
            name='num',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(default='Blank', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
