language: python

python:
  - 3.6
  - 3.7

services: postgresql

env:
  -DJANGO=1.8
install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE ci;" -U postgres

script:
  - python manage.py test --settings olly.ci_settings