language: python

python:
  - 3.7

services:
  - postgresql
  - docker

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE travis_ci_test;" -U postgres

script:
  - python manage.py test --settings olly.travis_settings

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

notifications:
  email:
    recipients:
      - nfm.studios@gmail.com
    on_success: never
    on_failure: always

deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin && docker build -t nfmstudios/project-olly:master . && docker push nfmstudios/project-olly:master
  on:
    branch: master