language: python

python:
  - 3.7

services:
  - postgresql
  - docker

addons:
  hosts:
    - project-olly-db

install:
  - docker build -t nfmstudios/project-olly:master .

before_script:
  - psql -c "CREATE DATABASE olly;" -U postgres
  - psql -c "CREATE USER olly WITH PASSWORD 'secret_password';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE olly to olly;" -U postgres

script:
  - docker run --network=host --env-file .env.example nfmstudios/project-olly:master python3 manage.py test

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

notifications:
  email:
    recipients:
      - nfm.studios@gmail.com
    on_success: never
    on_failure: always

deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin && docker push nfmstudios/project-olly:master
  on:
    branch: master