version: '3.3'

networks:
  project-olly-net:
    driver: bridge

services:
  project-olly-app:
    restart: always
    build: .
    depends_on:
      - project-olly-db
    volumes:
      - socket:/sock
      - ${static_path:-static}:/static
      - ${template_path:-templates}:/src/project-templates
    env_file: .env
    networks:
      - project-olly-net
    container_name: project-olly-app

  project-olly-db:
    restart: always
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=${db_password}
      - POSTGRES_USER=${db_username}
    networks:
      - project-olly-net
    volumes:
      - ./database:/var/lib/postgresql/data
    container_name: project-olly-db

  project-olly-proxy:
    restart: always
    image: abiosoft/caddy:no-stats
    depends_on:
      - project-olly-app
    environment:
      - ACME_AGREE=true
      - CADDYPATH=/etc/caddycerts
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - socket:/sock
      - ${static_path:-static}:/html/static
      - ${cert_path:-./certs}:/etc/caddycerts
    container_name: project-olly-proxy

volumes:
  socket:
  static:
  templates:
