# Generated by Django 2.0.2 on 2018-07-03 00:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180702_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),

    ]
