# Generated by Django 2.0.1 on 2018-03-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us', models.TextField(default='about us')),
                ('terms', models.TextField(default='terms of service')),
                ('privacy', models.TextField(default='privacy policy')),
            ],
        ),
    ]
