# Generated by Django 2.0.5 on 2018-09-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticinfo',
            name='welcomeln1',
            field=models.CharField(default='welcome text', max_length=25),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='welcomeln2',
            field=models.CharField(default='', max_length=25),
        ),
    ]
