# Generated by Django 2.0 on 2017-12-10 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Terms',
            new_name='StaticInfo',
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Privacy',
        ),
        migrations.RenameField(
            model_name='staticinfo',
            old_name='TOS',
            new_name='about_us',
        ),
    ]
