# Generated by Django 2.0.4 on 2018-04-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('website', models.CharField(blank=True, default='#', max_length=100)),
                ('twitter', models.CharField(blank=True, default='#', max_length=100)),
                ('bio', models.TextField()),
            ],
        ),
    ]
