# Generated by Django 2.2.15 on 2021-01-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialinfo',
            name='discord',
            field=models.URLField(blank=True, null=True, verbose_name='discord_server'),
        ),
    ]
