# Generated by Django 2.2.15 on 2021-04-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_socialinfo_discord'),
    ]

    operations = [
        migrations.CreateModel(
            name='OllySetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freeze_team_invites', models.BooleanField(default=False)),
                ('disable_team_creation', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Olly Settings',
            },
        ),
    ]
