# Generated by Django 2.0 on 2017-12-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20171209_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticinfo',
            name='privacy',
            field=models.TextField(default='privacy policy'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='terms',
            field=models.TextField(default='terms of service'),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='about_us',
            field=models.TextField(default='about us'),
        ),
    ]
