# Generated by Django 2.0.4 on 2018-09-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pages', '0002_auto_20180916_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticinfo',
            name='privacy',
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='slide1_img',
            field=models.ImageField(blank=True, upload_to='carousel_images'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='slide2_img',
            field=models.ImageField(blank=True, upload_to='carousel_images'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='slide3_img',
            field=models.ImageField(blank=True, upload_to='carousel_images'),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='welcomeln1',
            field=models.CharField(default='welcome1', max_length=25),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='welcomeln2',
            field=models.CharField(default='welcome2', max_length=25),
        ),
    ]
