# Generated by Django 2.0.4 on 2018-06-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticinfo',
            name='stream',
            field=models.CharField(default='twitch', max_length=25),
        ),
    ]
