# Generated by Django 2.0.4 on 2018-06-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_staticinfo_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticinfo',
            name='slide1link',
            field=models.TextField(default='#'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='slide2link',
            field=models.TextField(default='#'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='slide3link',
            field=models.TextField(default='#'),
        ),
    ]
