# Generated by Django 2.0.5 on 2018-10-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pages', '0003_auto_20180920_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticinfo',
            name='bingeslide1big',
            field=models.TextField(default='Coming Soon!'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='bingeslide1link',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='bingeslide1small',
            field=models.TextField(default='Coming Soon!'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='bingeslide2big',
            field=models.TextField(default='Coming Soon!'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='bingeslide2link',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='bingeslide2small',
            field=models.TextField(default='Coming Soon!'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='bingeslide3big',
            field=models.TextField(default='Coming Soon!'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='bingeslide3link',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='bingeslide3small',
            field=models.TextField(default='Coming Soon!'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='bingetop1',
            field=models.TextField(default='Coming Soon!'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='bingetop1link',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='bingetop2',
            field=models.TextField(default='Coming Soon!'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='bingetop2link',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='bingetop3',
            field=models.TextField(default='Coming Soon!'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='bingetop3link',
            field=models.URLField(default='#'),
        ),
    ]
