# Generated by Django 2.0.4 on 2018-10-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pages', '0004_auto_20181008_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticinfo',
            name='bingetop1image',
            field=models.ImageField(blank=True, upload_to='carousel_images'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='bingetop2image',
            field=models.ImageField(blank=True, upload_to='carousel_images'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='bingetop3image',
            field=models.ImageField(blank=True, upload_to='carousel_images'),
        ),
    ]
