# Generated by Django 2.0.4 on 2018-06-28 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20180610_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, upload_to='partner_images'),
        ),
    ]
