# Generated by Django 2.2.12 on 2021-07-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_ollysetting_whats_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='ollysetting',
            name='freeze_team_deletion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ollysetting',
            name='freeze_team_leaves',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ollysetting',
            name='freeze_team_player_removal',
            field=models.BooleanField(default=False),
        ),
    ]
