# Generated by Django 2.0.1 on 2018-06-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_partner_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='website',
            field=models.URLField(blank=True, default='#'),
        ),
    ]
