# Generated by Django 2.0.1 on 2018-07-03 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20180628_2221'),
        ('pages', '0006_auto_20180627_2254'),
    ]

    operations = [
    ]
