# Generated by Django 2.2.12 on 2021-08-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210727_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='redirects',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
