# Generated by Django 2.2.12 on 2021-08-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210803_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
