# Generated by Django 2.1.5 on 2019-02-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20190207_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticinfo',
            name='bingetop1linktxt',
            field=models.TextField(blank=True, default='Coming Soon!', null=True),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='bingetop2linktxt',
            field=models.TextField(blank=True, default='Coming Soon!', null=True),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='bingetop3linktxt',
            field=models.TextField(blank=True, default='Coming Soon!', null=True),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='bingetop4',
            field=models.TextField(blank=True, default='Coming Soon!', null=True),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='bingetop4image',
            field=models.ImageField(blank=True, upload_to='carousel_images'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='bingetop4link',
            field=models.URLField(blank=True, default='#', null=True),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='bingetop4linktxt',
            field=models.TextField(blank=True, default='Coming Soon!', null=True),
        ),
    ]
