# Generated by Django 2.1.7 on 2019-03-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20190217_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticinfo',
            name='bingeslide1link',
            field=models.URLField(blank=True, default='https://www.google.com', null=True),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='bingeslide2link',
            field=models.URLField(blank=True, default='https://www.google.com', null=True),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='bingeslide3link',
            field=models.URLField(blank=True, default='https://www.google.com', null=True),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='bingetop1link',
            field=models.URLField(blank=True, default='https://www.google.com', null=True),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='bingetop2link',
            field=models.URLField(blank=True, default='https://www.google.com', null=True),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='bingetop3link',
            field=models.URLField(blank=True, default='https://www.google.com', null=True),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='bingetop4link',
            field=models.URLField(blank=True, default='https://www.google.com', null=True),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='slide1link',
            field=models.TextField(blank=True, default='https://www.google.com', null=True),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='slide2link',
            field=models.TextField(blank=True, default='https://www.google.com', null=True),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='slide3link',
            field=models.TextField(blank=True, default='https://www.google.com', null=True),
        ),
    ]
