# Generated by Django 2.1.5 on 2019-03-13 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singletournaments', '0012_auto_20190112_1546'),
        ('pages', '0012_auto_20190312_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticinfo',
            name='featured_touranment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured_tournamet', to='singletournaments.SingleEliminationTournament'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website',
            field=models.URLField(blank=True, default='https://www.google.com'),
        ),
    ]
