# Generated by Django 2.1.5 on 2019-03-13 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20190313_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticinfo',
            name='featured_touranment',
        ),
    ]
