# Generated by Django 2.1.5 on 2019-03-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_staticinfo_featured_touranment'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticinfo',
            name='gatournament1',
            field=models.ImageField(blank=True, upload_to='carousel_images'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='gatournament1big',
            field=models.TextField(blank=True, default='Coming Soon!', null=True),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='gatournament1small',
            field=models.TextField(blank=True, default='Coming Soon!', null=True),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='gatournament2',
            field=models.ImageField(blank=True, upload_to='carousel_images'),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='gatournament2big',
            field=models.TextField(blank=True, default='Coming Soon!', null=True),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='gatournament2small',
            field=models.TextField(blank=True, default='Coming Soon!', null=True),
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='gatournamentbig',
            field=models.ImageField(blank=True, upload_to='carousel_images'),
        ),
    ]
