# Generated by Django 2.1.5 on 2019-03-28 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singletournaments', '0013_auto_20190313_1400'),
        ('pages', '0016_auto_20190327_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticinfo',
            name='featured_touranment',
        ),
        migrations.AddField(
            model_name='staticinfo',
            name='featured_tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featured_tournament', to='singletournaments.SingleEliminationTournament'),
        ),
    ]
