# Generated by Django 2.1.5 on 2019-04-26 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('pages', '0017_auto_20190328_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticinfo',
            name='featured_tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='featured_tournament',
                                    to='singletournaments.SingleEliminationTournament'),
        ),
    ]
