# Generated by Django 2.2.2 on 2019-06-05 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20190426_1727'),
        ('pages', '0018_auto_20190329_1930'),
    ]

    operations = [
    ]
