# Generated by Django 2.1.7 on 2019-05-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20190426_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitchchannel', models.URLField(blank=True, default='https://www.twitch.tv', null=True, verbose_name='twitch_channel')),
                ('youtubechannel', models.URLField(blank=True, default='https://www.youtube.com', null=True, verbose_name='youtube_channel')),
                ('twitterprofile', models.URLField(blank=True, default='https://www.twitter.com', null=True, verbose_name='twitter_profile')),
                ('facebookpage', models.URLField(blank=True, default='https://www.facebook.com', null=True, verbose_name='facebook_page')),
                ('instagrampage', models.URLField(blank=True, default='https://www.instagram.com', null=True, verbose_name='instagram_page')),
                ('stream', models.CharField(default='twitch', max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='staticinfo',
            name='facebookpage',
        ),
        migrations.RemoveField(
            model_name='staticinfo',
            name='instagrampage',
        ),
        migrations.RemoveField(
            model_name='staticinfo',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='staticinfo',
            name='twitchchannel',
        ),
        migrations.RemoveField(
            model_name='staticinfo',
            name='twitterprofile',
        ),
        migrations.RemoveField(
            model_name='staticinfo',
            name='youtubechannel',
        ),
    ]
