# Generated by Django 2.2.2 on 2019-06-05 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_merge_20190605_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticinfo',
            name='featured_tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_tournament', to='singletournaments.SingleEliminationTournament'),
        ),
    ]
