# Generated by Django 2.2.2 on 2019-06-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20190605_1916'),
        ('pages', '0019_auto_20190523_2257'),
    ]

    operations = [
    ]
