# Generated by Django 2.2.3 on 2020-04-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_auto_20200410_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialinfo',
            options={'verbose_name_plural': 'Social info'},
        ),
        migrations.AlterModelOptions(
            name='staticinfo',
            options={'verbose_name_plural': 'Static info'},
        ),
        migrations.AlterField(
            model_name='socialinfo',
            name='facebookpage',
            field=models.URLField(blank=True, null=True, verbose_name='facebook_page'),
        ),
        migrations.AlterField(
            model_name='socialinfo',
            name='instagrampage',
            field=models.URLField(blank=True, null=True, verbose_name='instagram_page'),
        ),
        migrations.AlterField(
            model_name='socialinfo',
            name='twitchchannel',
            field=models.URLField(blank=True, null=True, verbose_name='twitch_channel'),
        ),
        migrations.AlterField(
            model_name='socialinfo',
            name='twitterprofile',
            field=models.URLField(blank=True, null=True, verbose_name='twitter_profile'),
        ),
        migrations.AlterField(
            model_name='socialinfo',
            name='youtubechannel',
            field=models.URLField(blank=True, null=True, verbose_name='youtube_channel'),
        ),
    ]
