# Generated by Django 2.2.3 on 2020-04-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_auto_20200410_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialinfo',
            name='stream',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='block1link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='block2link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='block3link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='slide1link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='slide2link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='slide3link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
