# Generated by Django 2.2.3 on 2020-04-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_auto_20200410_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticinfo',
            name='slide1link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='slide2link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticinfo',
            name='slide3link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
