# Generated by Django 2.2.12 on 2020-04-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_auto_20200410_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontPageSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('subhead', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='carousel_images')),
            ],
            options={
                'verbose_name_plural': 'Front Page Slides',
            },
        ),
        migrations.RemoveField(
            model_name='staticinfo',
            name='slide1_img',
        ),
        migrations.RemoveField(
            model_name='staticinfo',
            name='slide1header',
        ),
        migrations.RemoveField(
            model_name='staticinfo',
            name='slide1link',
        ),
        migrations.RemoveField(
            model_name='staticinfo',
            name='slide1subhead',
        ),
        migrations.RemoveField(
            model_name='staticinfo',
            name='slide2_img',
        ),
        migrations.RemoveField(
            model_name='staticinfo',
            name='slide2header',
        ),
        migrations.RemoveField(
            model_name='staticinfo',
            name='slide2link',
        ),
        migrations.RemoveField(
            model_name='staticinfo',
            name='slide2subhead',
        ),
        migrations.RemoveField(
            model_name='staticinfo',
            name='slide3_img',
        ),
        migrations.RemoveField(
            model_name='staticinfo',
            name='slide3header',
        ),
        migrations.RemoveField(
            model_name='staticinfo',
            name='slide3link',
        ),
        migrations.RemoveField(
            model_name='staticinfo',
            name='slide3subhead',
        ),
        migrations.RemoveField(
            model_name='staticinfo',
            name='welcomeln1',
        ),
        migrations.RemoveField(
            model_name='staticinfo',
            name='welcomeln2',
        ),
    ]
