# Generated by Django 2.1.5 on 2019-04-04 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0005_team_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0007_auto_20190112_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='WagerChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(default='No additional info given')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_team', to='teams.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WagerMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_obj', to='matches.Match')),
            ],
        ),
        migrations.CreateModel(
            name='WagerRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('challenge_accepted', models.BooleanField(default=False)),
                ('expiration', models.DateTimeField(null=True)),
                ('credits', models.PositiveIntegerField(default=5)),
                ('bestof', models.SmallIntegerField(choices=[(0, 'Best of 1'), (1, 'Best of 3'), (2, 'Best of 5'), (3, 'Best of 7'), (4, 'Best of 9')], default=0)),
                ('teamformat', models.SmallIntegerField(choices=[(0, '1v1'), (1, '2v2'), (2, '3v3'), (3, '4v4'), (4, '5v5'), (5, '6v6')], default=1)),
                ('info', models.TextField(default='No additional info given')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_user', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_choices', to='matches.GameChoice')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_choices', to='matches.PlatformChoice')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesting_team', to='teams.Team')),
            ],
        ),
    ]
