# Generated by Django 2.1.5 on 2019-04-26 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('wagers', '0002_wagerrequest_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagerrequest',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_user',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
