# Generated by Django 2.1.5 on 2019-04-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wagers', '0003_auto_20190426_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagerchallenge',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
