# Generated by Django 2.1.7 on 2019-05-14 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagers', '0004_wagerchallenge_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagerrequest',
            name='challenge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wager_challenge', to='wagers.WagerChallenge'),
        ),
    ]
