# Generated by Django 2.1.7 on 2019-05-14 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagers', '0005_wagerrequest_challenge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wagerchallenge',
            old_name='confirmed',
            new_name='confirm',
        ),
    ]
