# Generated by Django 2.1.5 on 2019-05-23 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagers', '0006_auto_20190514_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wagerchallenge',
            old_name='user',
            new_name='creator',
        ),
    ]
