# Generated by Django 2.1.7 on 2019-05-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagers', '0007_auto_20190523_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagermatch',
            name='credits',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
