# Generated by Django 2.1.7 on 2019-05-24 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagers', '0008_wagermatch_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagerrequest',
            name='wmatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wmatch', to='wagers.WagerMatch'),
        ),
    ]
