# Generated by Django 2.2.2 on 2019-07-13 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagers', '0009_wagerrequest_wmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagerrequest',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_choices', to='matches.GameChoice'),
        ),
        migrations.AlterField(
            model_name='wagerrequest',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_choices', to='matches.PlatformChoice'),
        ),
    ]
