# Generated by Django 2.0.3 on 2018-03-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'New'), (1, 'On Hold'), (2, 'In Progress'), (3, 'Closed')], default=0),
        ),
    ]
