# Generated by Django 2.0 on 2018-03-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_auto_20180301_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('prize claim', 'Prize Claim'), ('tournament support', 'Tournament Support'), ('billing', 'Billing'), ('refund request', 'Refund Request'), ('psn/xbl issues', 'PSN/XBL Issues'), ('match support/dispute', 'Match Support/Dispute')], default='general', max_length=15),
        ),
    ]
