# Generated by Django 2.0 on 2018-03-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_auto_20180302_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.SmallIntegerField(choices=[(0, 'General'), (1, 'Prize Claim'), (2, 'Tournament Support'), (3, 'Billing'), (4, 'Refund Request'), (5, 'PSN/XBL Issues'), (6, 'Match Support/Dispute')], default=0),
        ),
    ]
