# Generated by Django 2.2.15 on 2020-12-09 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        ('matches', '0002_auto_20201209_1508'),
        ('teams', '0001_initial'),
        ('profiles', '0001_initial'),
        ('singletournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='league_team', to='teams.Team'),
        ),
        migrations.AddField(
            model_name='leaguefreeagent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fa_profile', to='profiles.UserProfile'),
        ),
        migrations.AddField(
            model_name='leaguedivision',
            name='matches',
            field=models.ManyToManyField(blank=True, to='matches.Match'),
        ),
        migrations.AddField(
            model_name='leaguedivision',
            name='teams',
            field=models.ManyToManyField(blank=True, to='leagues.LeagueTeam'),
        ),
        migrations.AddField(
            model_name='league',
            name='divisions',
            field=models.ManyToManyField(blank=True, to='leagues.LeagueDivision'),
        ),
        migrations.AddField(
            model_name='league',
            name='fa',
            field=models.ManyToManyField(blank=True, related_name='league_fas', to='leagues.LeagueFreeAgent'),
        ),
        migrations.AddField(
            model_name='league',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='league_game', to='matches.GameChoice'),
        ),
        migrations.AddField(
            model_name='league',
            name='maps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='league_maps', to='matches.MapPoolChoice'),
        ),
        migrations.AddField(
            model_name='league',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='league_platform', to='matches.PlatformChoice'),
        ),
        migrations.AddField(
            model_name='league',
            name='ruleset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='league_ruleset', to='singletournaments.SingleTournamentRuleset'),
        ),
        migrations.AddField(
            model_name='league',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='league_settings', to='leagues.LeagueSettings'),
        ),
        migrations.AddField(
            model_name='league',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='league_sport', to='matches.SportChoice'),
        ),
        migrations.AddField(
            model_name='league',
            name='teams',
            field=models.ManyToManyField(blank=True, to='leagues.LeagueTeam'),
        ),
    ]
