# Generated by Django 2.2.12 on 2020-05-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_league_maps'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='credits',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='league',
            name='size',
            field=models.PositiveSmallIntegerField(default=8),
        ),
    ]
