# Generated by Django 2.2.12 on 2020-05-16 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_auto_20200515_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaguesettings',
            old_name='num_divisons',
            new_name='num_divisions',
        ),
    ]
