# Generated by Django 2.2.15 on 2021-04-05 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_auto_20201209_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueMatchScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(default='Default Match Scheduler', max_length=35)),
                ('matches_per_day', models.PositiveSmallIntegerField(default=1)),
                ('matches_per_week', models.PositiveSmallIntegerField(default=2)),
                ('match_days', models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=1)),
                ('match_times_same', models.BooleanField(default=True)),
                ('match_time', models.TimeField(blank=True, null=True)),
                ('total_matches', models.PositiveSmallIntegerField(default=10)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='scheduler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leagues.LeagueMatchScheduler'),
        ),
    ]
