# Generated by Django 2.2.12 on 2021-05-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_match_conference_match'),
        ('leagues', '0004_auto_20201209_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='non_conference',
            field=models.ManyToManyField(related_name='non_conference_matches', to='matches.Match'),
        ),
    ]
