# Generated by Django 2.2.12 on 2020-05-16 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_auto_20200515_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaguesettings',
            name='record_format',
        ),
    ]
