# Generated by Django 2.2.12 on 2020-05-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_remove_leaguesettings_record_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='disable_userreport',
            field=models.BooleanField(default=False),
        ),
    ]
