# Generated by Django 2.2.12 on 2021-08-10 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_league_non_conference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leagueteam',
            options={'ordering': ['-points']},
        ),
    ]
