# Generated by Django 2.2.12 on 2020-05-16 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_league_disable_userreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='credits',
            new_name='req_credits',
        ),
    ]
