# Generated by Django 2.2.12 on 2021-08-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_match_conference_match'),
        ('leagues', '0006_auto_20210810_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='featured_matches',
            field=models.ManyToManyField(blank=True, related_name='featured_matches', to='matches.Match'),
        ),
        migrations.AddField(
            model_name='league',
            name='featured_players',
            field=models.ManyToManyField(blank=True, related_name='featured_players', to='matches.Match'),
        ),
        migrations.AddField(
            model_name='league',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('preseason', 'Preseason'), ('regular season', 'Regular Season'), ('playoffs', 'Playoffs'), ('finals', 'Finals'), ('offseason', 'Offseason')], default='preseason', max_length=50),
        ),
        migrations.AlterField(
            model_name='league',
            name='non_conference',
            field=models.ManyToManyField(blank=True, related_name='non_conference_matches', to='matches.Match'),
        ),
    ]
