# Generated by Django 2.2.12 on 2020-05-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_auto_20200516_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='divisions',
            field=models.ManyToManyField(blank=True, null=True, to='leagues.LeagueDivision'),
        ),
    ]
