# Generated by Django 2.2.12 on 2020-05-16 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0009_auto_20200516_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='divisions',
            field=models.ManyToManyField(blank=True, to='leagues.LeagueDivision'),
        ),
        migrations.AlterField(
            model_name='league',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='league_game', to='matches.GameChoice'),
        ),
        migrations.AlterField(
            model_name='league',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='league_platform', to='matches.PlatformChoice'),
        ),
    ]
