# Generated by Django 2.2.12 on 2020-05-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0010_auto_20200516_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='league_images'),
        ),
    ]
