# Generated by Django 2.2.12 on 2020-05-16 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0011_auto_20200516_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='maps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='league_maps', to='matches.MapPoolChoice'),
        ),
    ]
