# Generated by Django 2.2.12 on 2020-05-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0013_leaguesettings_auto_matchup'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='teams',
            field=models.ManyToManyField(blank=True, to='leagues.LeagueTeam'),
        ),
    ]
