# Generated by Django 2.2.14 on 2020-07-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0015_auto_20200726_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='teams',
            field=models.ManyToManyField(blank=True, to='leagues.LeagueTeam'),
        ),
    ]
