# Generated by Django 2.0.1 on 2018-03-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singletournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleeliminationtournament',
            name='name',
            field=models.CharField(default='No name provided', max_length=50, unique=True),
        ),
    ]
