# Generated by Django 2.0.2 on 2018-03-14 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singletournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleeliminationtournament',
            name='rules',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournamentrules', to='matches.RuleSet'),
        ),
        migrations.DeleteModel(
            name='RuleSet',
        ),
    ]
