# Generated by Django 2.0.1 on 2018-03-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singletournaments', '0002_auto_20180314_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleeliminationtournament',
            name='prize1',
            field=models.CharField(default='no prize specified', max_length=250),
        ),
        migrations.AddField(
            model_name='singleeliminationtournament',
            name='prize2',
            field=models.CharField(default='no prize specified', max_length=250),
        ),
        migrations.AddField(
            model_name='singleeliminationtournament',
            name='prize3',
            field=models.CharField(default='no prize specified', max_length=250),
        ),
        migrations.AlterField(
            model_name='singleeliminationtournament',
            name='size',
            field=models.PositiveSmallIntegerField(choices=[(4, 4), (8, 8), (16, 16), (32, 32), (64, 64), (128, 128)], default=32),
        ),
    ]
