# Generated by Django 2.0.2 on 2018-03-29 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singletournaments', '0002_remove_singleeliminationtournament_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleeliminationtournament',
            name='second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondplaceteam', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='singleeliminationtournament',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winningteam', to='teams.Team'),
        ),
    ]
