# Generated by Django 2.0.1 on 2018-09-14 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singletournaments', '0002_singleeliminationtournament_third'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleeliminationtournament',
            name='ruleset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournamentruleset', to='singletournaments.SingleTournamentRuleset'),
        ),
    ]
