# Generated by Django 2.0.4 on 2018-04-12 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singletournaments', '0002_auto_20180329_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singletournamentround',
            name='teams',
        ),
    ]
