# Generated by Django 2.0.8 on 2018-11-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singletournaments', '0003_auto_20180914_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleeliminationtournament',
            name='xp_seed',
            field=models.BooleanField(default=False),
        ),
    ]
