# Generated by Django 2.0 on 2018-04-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singletournaments', '0003_remove_singletournamentround_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleeliminationtournament',
            name='bracket_generated',
            field=models.BooleanField(default=False),
        ),
    ]
