# Generated by Django 2.0.4 on 2018-10-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singletournaments', '0003_auto_20180914_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleeliminationtournament',
            name='image',
            field=models.ImageField(blank=True, upload_to='tournament_images'),
        ),
    ]
