# Generated by Django 2.0.1 on 2018-03-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singletournaments', '0003_auto_20180318_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleeliminationtournament',
            name='prize1',
            field=models.CharField(default='no prize specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='singleeliminationtournament',
            name='prize2',
            field=models.CharField(default='no prize specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='singleeliminationtournament',
            name='prize3',
            field=models.CharField(default='no prize specified', max_length=50),
        ),
    ]
