# Generated by Django 2.0.1 on 2018-03-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('singletournaments', '0004_auto_20180318_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleeliminationtournament',
            name='teams',
            field=models.ManyToManyField(to='teams.Team'),
        ),
    ]
