# Generated by Django 2.0.3 on 2018-04-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singletournaments', '0004_singleeliminationtournament_bracket_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleeliminationtournament',
            name='current_round',
            field=models.SmallIntegerField(default=1),
        ),
    ]
