# Generated by Django 2.0.4 on 2018-04-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singletournaments', '0005_singleeliminationtournament_current_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleeliminationtournament',
            name='current_round',
            field=models.SmallIntegerField(blank=True, default=1),
        ),
    ]
