# Generated by Django 2.0.1 on 2018-06-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singletournaments', '0006_auto_20180424_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singletournamentteam',
            name='seed',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
