# Generated by Django 2.0.9 on 2018-10-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('singletournaments', '0006_auto_20181018_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleeliminationtournament',
            name='allow_register',
            field=models.BooleanField(default=False),
        ),
    ]
