# Generated by Django 2.0.9 on 2018-11-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('singletournaments', '0007_singleeliminationtournament_allow_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleeliminationtournament',
            name='twitch',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
