# Generated by Django 2.0.8 on 2018-11-09 21:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('singletournaments', '0007_singleeliminationtournament_allow_register'),
        ('singletournaments', '0004_singleeliminationtournament_xp_seed'),
    ]

    operations = [
    ]
