# Generated by Django 2.0.1 on 2018-06-21 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singletournaments', '0008_singleeliminationtournament_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singletournamentteam',
            name='round',
        ),
    ]
