# Generated by Django 2.0.8 on 2018-11-18 05:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('singletournaments', '0009_singletournamentround_info'),
        ('singletournaments', '0008_merge_20181109_2110'),
    ]

    operations = [
    ]
