# Generated by Django 2.0.4 on 2019-01-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('singletournaments', '0010_merge_20181118_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleeliminationtournament',
            name='game',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='singleeliminationtournament',
            name='platform',
            field=models.SmallIntegerField(default=0),
        ),
    ]
