# Generated by Django 2.0.1 on 2018-06-28 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singletournaments', '0010_auto_20180626_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleeliminationtournament',
            name='ruleset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournamentruleset', to='singletournaments.SingleTournamentRuleset'),
        ),
    ]
