# Generated by Django 2.0.4 on 2019-01-12 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('singletournaments', '0011_auto_20190112_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleeliminationtournament',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.GameChoice'),
        ),
        migrations.AlterField(
            model_name='singleeliminationtournament',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.PlatformChoice'),
        ),
    ]
