# Generated by Django 2.1.5 on 2019-03-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singletournaments', '0012_auto_20190112_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleeliminationtournament',
            name='twitch',
            field=models.CharField(default='twitch', max_length=60),
        ),
    ]
