# Generated by Django 2.1.5 on 2019-03-29 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singletournaments', '0013_auto_20190313_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleeliminationtournament',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='matches.GameChoice'),
        ),
    ]
