# Generated by Django 2.1.7 on 2019-06-02 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singletournaments', '0014_singleeliminationtournament_map_pool'),
        ('singletournaments', '0014_auto_20190329_1944'),
    ]

    operations = [
    ]
