# Generated by Django 2.2.2 on 2019-07-13 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singletournaments', '0015_merge_20190602_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleeliminationtournament',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game', to='matches.GameChoice'),
        ),
        migrations.AlterField(
            model_name='singleeliminationtournament',
            name='map_pool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='map_pool', to='matches.MapPoolChoice'),
        ),
        migrations.AlterField(
            model_name='singleeliminationtournament',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matches.PlatformChoice'),
        ),
        migrations.AlterField(
            model_name='singleeliminationtournament',
            name='ruleset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournamentruleset', to='singletournaments.SingleTournamentRuleset'),
        ),
        migrations.AlterField(
            model_name='singleeliminationtournament',
            name='second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondplaceteam', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='singleeliminationtournament',
            name='third',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thirdplaceteam', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='singleeliminationtournament',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winningteam', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='singletournamentruleset',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rulesetCreator', to=settings.AUTH_USER_MODEL),
        ),
    ]
