# Generated by Django 2.2.7 on 2020-01-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singletournaments', '0016_auto_20190713_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleeliminationtournament',
            name='disable_userreports',
            field=models.BooleanField(default=True),
        ),
    ]
