# Generated by Django 2.2.7 on 2020-01-15 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singletournaments', '0018_auto_20200115_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singleeliminationtournament',
            old_name='sports',
            new_name='sport',
        ),
    ]
