# Generated by Django 2.2.7 on 2020-01-15 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singletournaments', '0019_auto_20200115_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singleeliminationtournament',
            old_name='disable_userreports',
            new_name='disable_userreport',
        ),
    ]
