# Generated by Django 2.2.12 on 2020-04-20 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('singletournaments', '0020_auto_20200115_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleeliminationtournament',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game', to='matches.GameChoice'),
        ),
        migrations.AlterField(
            model_name='singleeliminationtournament',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='matches.PlatformChoice'),
        ),
        migrations.AlterField(
            model_name='singleeliminationtournament',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sport', to='matches.SportChoice'),
        ),
    ]
